[package]
name = "elmo"
version = "0.1.0"
authors = ["Timur <timur.makarchuk@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
reqwest = "0.9.15"
itertools = "0.8.0"